version: '3.8'
services:
  app:
    image: ${IMAGE?Variable not set}:${TAG?Variable not set}
    container_name: account-manager
      #ports:
      #  - target: 5000
      #    published: 8095
      #    protocol: tcp
      #    mode: ingress
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.account-manager_app.rule=Host(`${HOST?Variable not set}`)"
        - 'traefik.http.services.account-manager_app.loadbalancer.server.port=5000'  
        - "traefik.http.routers.account-manager_app.entrypoints=web"
      mode: replicated
      replicas: 2
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

    healthcheck:
      test: curl --fail http://localhost:5000/accountico/heartbeat || exit 1
      interval: 40s
      timeout: 10s
      retries: 3
      start_period: 30s      
    env_file: .env
    environment:
      - TZ=Asia/Tehran
      - NODE_ENV=production 
    networks:
      - app
      - traefik-public
networks:
  app:
   external: true
  traefik-public:
   external: true